name: CI - Preview

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["dev", "staging", "main", "release/**"]

jobs:
  update:
    name: Publish Preview Channel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Ensure lightningcss is installed
        run: bun add lightningcss

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Get branch name
        id: branch-name
        run: echo "current_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: EAS update (PR, non-main)
        if: github.event_name == 'pull_request' && steps.branch-name.outputs.current_branch != 'main'
        run: bunx eas update --branch ${{ steps.branch-name.outputs.current_branch }} --message "${{ github.event.pull_request.title }}"

      - name: EAS update (PR, main)
        if: github.event_name == 'pull_request' && steps.branch-name.outputs.current_branch == 'main'
        run: bunx eas update --branch ${{ steps.branch-name.outputs.current_branch }} --message "${{ github.event.pull_request.title }}"

      - name: EAS update (Push, non-main)
        if: github.event_name == 'push' && steps.branch-name.outputs.current_branch != 'main'
        run: bunx eas update --branch ${{ steps.branch-name.outputs.current_branch }} --message "${{ github.event.head_commit.message }}"

      - name: EAS update (Push, main)
        if: github.event_name == 'push' && steps.branch-name.outputs.current_branch == 'main'
        run: bunx eas update --branch ${{ steps.branch-name.outputs.current_branch }} --message "${{ github.event.head_commit.message }}"