name: ESLint

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["dev", "staging", "main"]

jobs:
  lint:
    name: Run ESLint rules checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        run: yarn lint