name: ESLint

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["dev", "staging", "main"]

jobs:
  lint:
    name: Run ESLint rules checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH  # Add Bun to PATH

      - name: Install dependencies
        run: bun install

      - name: Run linters
        run: yarn lint